// export const UPDATE_PROJECTS = "UPDATE_PROJECTS";
export const EDIT_PROJECT_NAME = "EDIT_PROJECT_NAME";
export const EDIT_PROJECT_DESCRIPTION = "EDIT_PROJECT_DESCRIPTION";
export const SET_PROJECT_HOURS = "SET_PROJECT_HOURS";
export const UPDATE_PROJECT_USED_HOURS = "UPDATE_PROJECT_USED_HOURS";
export const SET_MANAGER = "SET_MANAGER";
export const SET_LOADING = "SET_LOADING";
export const SET_ERROR = "SET_ERROR";
